### PR TITLE
util/mtp-hotplug -W

### PR DESCRIPTION
**Pull request by JoesCat**
Assemble 69-libmtp.hwdb sorted by idVendor:idProduct.

This can be considered a minor improvement if doing a binary search of this database by idVendor:idProduct (It is better to sort this database once during build versus sorting everytime this database is loaded).

This option was quick to create since most of the code exists already for mtp-hotplug -f

NOTE: If the database is searched sequentially, then there's no speed improvement with util/mtp-hotplug -W

### CODE REVIEW

**Comment by msmeissn** [comment]
Do you know anyone that uses this db and does not put in some form of hashed table ?

I think udev does it the right way already

**Comment by JoesCat** [comment]
Nothing wrong with it as it exists now - otherwise it would have been flagged as a bug back then.

Just another set of eyes looking at the code, and thinking, maybe this can be improved a little bit.
Logic being....
Sort "once" during the build of this particular file....
...to reduce the work of sorting by "each/every" user's machine, every boot-up/load of this file.

Summary, a bit of work done once by the installer/distro, benefits everyone downstream

Most of the code already exists to create this option, so it didn't appear to be a big leap to create this option :-)
If it looks useful downstream, it's available.

**Comment by msmeissn** [comment]
I want to avoid having too much options, so I would suggest to just change the hwdb output by default to be the sorted one.

**Comment by JoesCat** [comment]
Makes sense.
Patch simplifies down to a one-liner.
Resolved.

**Pull request merged**
